Runtime common
darwinia-network/darwinia-2.0 pull request #32
Opened 2022-11-10 08:08 UTC by jiguantong

- [ ] xcm_config
- [ ] descend_origin barrier
- [ ] helixbridge

2022-11-14 12:08 UTC, AurevoirXavier commented
If you merge the main, the CI problems will be gone.

2022-11-15 05:03 UTC, AurevoirXavier commented on runtime/common/Cargo.toml
> +ethereum-types = { version = "0.13.1", default-features = false, features = ["rlp", "codec"] }
Please check the `[dependencies]`.

Found a lot of unused dependencies.

2022-11-15 05:29 UTC, AurevoirXavier requested changes
Please resolve the review comments.

2022-11-15 05:59 UTC, AsceticBear commented on node/Cargo.toml
> +
A nitpick. Empty line

2022-11-15 06:00 UTC, AsceticBear commented on runtime/common/Cargo.toml
> +repository  = "https://github.com/darwinia-network/darwinia-parachain"
Should be `repository  = "https://github.com/darwinia-network/darwinia"`

2022-11-15 12:01 UTC, AsceticBear commented on runtime/common/src/xcm_barrier.rs
> +	};
@AurevoirXavier Please help review this. I am okay with other changes.

2022-11-15 12:01 UTC, AsceticBear approved these changes

2022-11-15 13:21 UTC, merged